{
 "title": "Kafka Kraft 4.4.1",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Nombre de Topics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_globaltopiccount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre de Controllers actifs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre de Brokers actifs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activebrokercount",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}